# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb-example.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10pb-example.proto\"r\n\x07Request\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x0c\n\x04seqn\x18\x02 \x01(\x05\x12\x1b\n\x04type\x18\x03 \x01(\x0e\x32\r.Request.Type\x12\x0f\n\x07payload\x18\x04 \x01(\t\"\x1a\n\x04Type\x12\x08\n\x04\x45\x43HO\x10\x00\x12\x08\n\x04RCMD\x10\x01\"7\n\x05Reply\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x0c\n\x04seqn\x18\x02 \x01(\x05\x12\x0f\n\x07payload\x18\x03 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pb_example_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=20
  _REQUEST._serialized_end=134
  _REQUEST_TYPE._serialized_start=108
  _REQUEST_TYPE._serialized_end=134
  _REPLY._serialized_start=136
  _REPLY._serialized_end=191
# @@protoc_insertion_point(module_scope)
